package com.rfid.rru9809;
import com.ochafik.lang.jnaerator.runtime.globals.GlobalInt;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;

import java.io.File;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>com.rfid.rru9809</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ComRfidRru9809Library extends Library {
    public static final String JNA_LIBRARY_NAME = "com.rfid.rru9809";
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ComRfidRru9809Library.JNA_LIBRARY_NAME);

    String fileName = "com.rfid.rru9809.dll";

    public static final ComRfidRru9809Library INSTANCE = (ComRfidRru9809Library)Native.loadLibrary(ComRfidRru9809Library.JNA_LIBRARY_NAME, ComRfidRru9809Library.class);

    /**
     * Original signature : <code>int fnRRU9809()</code><br>
     * <i>native declaration : line 23</i>
     */
    int fnRRU9809();
    /**
     * Original signature : <code>int OpenCom(int, unsigned char)</code><br>
     * <i>native declaration : line 27</i>
     */
    int OpenCom(int portNumber, byte fbaud);
    /**
     * Original signature : <code>int OpenComPort(int, unsigned char*, unsigned char, int*)</code><br>
     * <i>native declaration : line 28</i><br>
     * @deprecated use the safer methods {@link #OpenComPort(int, ByteBuffer, byte, IntBuffer)} and {@link #OpenComPort(int, com.sun.jna.Pointer, byte, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int OpenComPort(int port, Pointer address, byte baud, IntByReference FrmHandle);
    /**
     * Original signature : <code>int OpenComPort(int, unsigned char*, unsigned char, int*)</code><br>
     * <i>native declaration : line 28</i>
     */
    int OpenComPort(int port, ByteBuffer address, byte baud, IntBuffer FrmHandle);
    /**
     * Original signature : <code>int AutoOpenComPort(int*, unsigned char*, unsigned char, int*)</code><br>
     * <i>native declaration : line 29</i><br>
     * @deprecated use the safer methods {@link #AutoOpenComPort(IntBuffer, ByteBuffer, byte, IntBuffer)} and {@link #AutoOpenComPort(com.sun.jna.ptr.IntByReference, com.sun.jna.Pointer, byte, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int AutoOpenComPort(IntByReference port, Pointer address, byte baud, IntByReference FrmHandle);
    /**
     * Original signature : <code>int AutoOpenComPort(int*, unsigned char*, unsigned char, int*)</code><br>
     * <i>native declaration : line 29</i>
     */
    int AutoOpenComPort(IntBuffer port, ByteBuffer address, byte baud, IntBuffer FrmHandle);
    /**
     * Original signature : <code>int CloseComPort()</code><br>
     * <i>native declaration : line 30</i>
     */
    int CloseComPort();
    /**
     * Original signature : <code>int CloseSpecComPort(int)</code><br>
     * <i>native declaration : line 31</i>
     */
    int CloseSpecComPort(int FrmHandle);
    /**
     * Original signature : <code>int WriteCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, int*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 32</i><br>
     * @deprecated use the safer methods {@link #WriteCard_G2(ByteBuffer, ByteBuffer, byte, byte, byte, ByteBuffer, ByteBuffer, byte, byte, byte, IntBuffer, byte, IntBuffer, int)} and {@link #WriteCard_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.ptr.IntByReference, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
//    @Deprecated
//    int WriteCard_G2(Pointer address, Pointer EPC, byte Mem, byte WordPtr, byte Writedatalen, Pointer Writedata, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, IntByReference WrittenDataNum, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, int*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 32</i>
     */
    int WriteCard_G2(ByteBuffer address, ByteBuffer EPC, byte Mem, byte WordPtr, byte Writedatalen, ByteBuffer Writedata, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, IntBuffer WrittenDataNum, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteBlock_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, int*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 46</i><br>
     * @deprecated use the safer methods {@link #WriteBlock_G2(ByteBuffer, ByteBuffer, byte, byte, byte, ByteBuffer, ByteBuffer, byte, byte, byte, IntBuffer, byte, IntBuffer, int)} and {@link #WriteBlock_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.ptr.IntByReference, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int WriteBlock_G2(Pointer address, Pointer EPC, byte Mem, byte WordPtr, byte Writedatalen, Pointer Writedata, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, IntByReference WrittenDataNum, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteBlock_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, int*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 46</i>
     */
    int WriteBlock_G2(ByteBuffer address, ByteBuffer EPC, byte Mem, byte WordPtr, byte Writedatalen, ByteBuffer Writedata, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, IntBuffer WrittenDataNum, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int ReadCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 60</i><br>
     * @deprecated use the safer methods {@link #ReadCard_G2(ByteBuffer, ByteBuffer, byte, byte, byte, ByteBuffer, byte, byte, byte, ByteBuffer, byte, IntBuffer, int)} and {@link #ReadCard_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
//    @Deprecated
//    int ReadCard_G2(Pointer address, Pointer EPC, byte Mem, byte WordPtr, byte Num, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, Pointer Data, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int ReadCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 60</i>
     */
    int ReadCard_G2(ByteBuffer address, ByteBuffer EPC, byte Mem, byte WordPtr, byte Num, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, ByteBuffer Data, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int Inventory_G2(unsigned char*, unsigned char*, int*, int*, int)</code><br>
     * <i>native declaration : line 73</i><br>
     * @deprecated use the safer methods {@link #Inventory_G2(ByteBuffer, ByteBuffer, IntBuffer, IntBuffer, int)} and {@link #Inventory_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int Inventory_G2(Pointer address, Pointer pOUcharIDList, IntByReference Totallen, IntByReference CardNum, int FrmHandle);
    /**
     * Original signature : <code>int Inventory_G2(unsigned char*, unsigned char*, int*, int*, int)</code><br>
     * <i>native declaration : line 73</i>
     */
    int Inventory_G2(ByteBuffer address, ByteBuffer pOUcharIDList, IntBuffer Totallen, IntBuffer CardNum, int FrmHandle);
    /**
     * \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00d8\u00d6\u00b7<br>
     * Original signature : <code>int GetReaderInformation(unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, int)</code><br>
     * @param ComAdr \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00d8\u00d6\u00b7<br>
     * @param VersionInfo \u00c8\u00ed\u00bc\u00fe\u00b0\u00e6\u00b1\u00be<br>
     * @param ReaderType \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00d0\u00cd\u00ba\u00c5<br>
     * @param TrType \u00d6\u00a7\u00b3\u00d6\u00b5\u00c4\u00d0\u00ad\u00d2\u00e9<br>
     * @param dmaxfre \u00b5\u00b1\u00c7\u00b0\u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00ca\u00b9\u00d3\u00c3\u00b5\u00c4\u00d7\u00ee\u00b8\u00df\u00c6\u00b5\u00c2\u00ca<br>
     * @param dminfre \u00b5\u00b1\u00c7\u00b0\u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00ca\u00b9\u00d3\u00c3\u00b5\u00c4\u00d7\u00ee\u00b5\u00cd\u00c6\u00b5\u00c2\u00ca<br>
     * @param powerdBm \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00c4\u00ca\u00e4\u00b3\u00f6\u00b9\u00a6\u00c2\u00ca<br>
     * <i>native declaration : line 78</i><br>
     * @deprecated use the safer methods {@link #GetReaderInformation(ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, int)} and {@link #GetReaderInformation(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int GetReaderInformation(Pointer ComAdr, Pointer VersionInfo, Pointer ReaderType, Pointer TrType, Pointer dmaxfre, Pointer dminfre, Pointer powerdBm, Pointer ScanTime, int FrmHandle);
    /**
     * \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00d8\u00d6\u00b7<br>
     * Original signature : <code>int GetReaderInformation(unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, unsigned char*, int)</code><br>
     * @param ComAdr \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00d8\u00d6\u00b7<br>
     * @param VersionInfo \u00c8\u00ed\u00bc\u00fe\u00b0\u00e6\u00b1\u00be<br>
     * @param ReaderType \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00d0\u00cd\u00ba\u00c5<br>
     * @param TrType \u00d6\u00a7\u00b3\u00d6\u00b5\u00c4\u00d0\u00ad\u00d2\u00e9<br>
     * @param dmaxfre \u00b5\u00b1\u00c7\u00b0\u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00ca\u00b9\u00d3\u00c3\u00b5\u00c4\u00d7\u00ee\u00b8\u00df\u00c6\u00b5\u00c2\u00ca<br>
     * @param dminfre \u00b5\u00b1\u00c7\u00b0\u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00ca\u00b9\u00d3\u00c3\u00b5\u00c4\u00d7\u00ee\u00b5\u00cd\u00c6\u00b5\u00c2\u00ca<br>
     * @param powerdBm \u00b6\u00c1\u00d0\u00b4\u00c6\u00f7\u00b5\u00c4\u00ca\u00e4\u00b3\u00f6\u00b9\u00a6\u00c2\u00ca<br>
     * <i>native declaration : line 78</i>
     */
    int GetReaderInformation(ByteBuffer ComAdr, ByteBuffer VersionInfo, ByteBuffer ReaderType, ByteBuffer TrType, ByteBuffer dmaxfre, ByteBuffer dminfre, ByteBuffer powerdBm, ByteBuffer ScanTime, int FrmHandle);
    /**
     * Original signature : <code>int SetEASAlarm_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 87</i><br>
     * @deprecated use the safer methods {@link #SetEASAlarm_G2(ByteBuffer, ByteBuffer, ByteBuffer, byte, byte, byte, byte, byte, IntBuffer, int)} and {@link #SetEASAlarm_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int SetEASAlarm_G2(Pointer address, Pointer EPC, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte EAS, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetEASAlarm_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 87</i>
     */
    int SetEASAlarm_G2(ByteBuffer address, ByteBuffer EPC, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte EAS, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckEASAlarm_G2(unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 97</i><br>
     * @deprecated use the safer methods {@link #CheckEASAlarm_G2(ByteBuffer, IntBuffer, int)} and {@link #CheckEASAlarm_G2(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int CheckEASAlarm_G2(Pointer address, IntByReference Eerrorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckEASAlarm_G2(unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 97</i>
     */
    int CheckEASAlarm_G2(ByteBuffer address, IntBuffer Eerrorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetCardProtect_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 98</i><br>
     * @deprecated use the safer methods {@link #SetCardProtect_G2(ByteBuffer, ByteBuffer, byte, byte, ByteBuffer, byte, byte, byte, byte, IntBuffer, int)} and {@link #SetCardProtect_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, com.sun.jna.Pointer, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int SetCardProtect_G2(Pointer address, Pointer EPC, byte select, byte setprotect, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetCardProtect_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 98</i>
     */
    int SetCardProtect_G2(ByteBuffer address, ByteBuffer EPC, byte select, byte setprotect, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int Writedfre(unsigned char*, unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 109</i><br>
     * @deprecated use the safer methods {@link #Writedfre(ByteBuffer, ByteBuffer, ByteBuffer, int)} and {@link #Writedfre(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int Writedfre(Pointer address, Pointer dmaxfre, Pointer dminfre, int FrmHandle);
    /**
     * Original signature : <code>int Writedfre(unsigned char*, unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 109</i>
     */
    int Writedfre(ByteBuffer address, ByteBuffer dmaxfre, ByteBuffer dminfre, int FrmHandle);
    /**
     * Original signature : <code>int WriteComAdr(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 113</i><br>
     * @deprecated use the safer methods {@link #WriteComAdr(ByteBuffer, ByteBuffer, int)} and {@link #WriteComAdr(com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int WriteComAdr(Pointer address, Pointer ComAdrData, int FrmHandle);
    /**
     * Original signature : <code>int WriteComAdr(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 113</i>
     */
    int WriteComAdr(ByteBuffer address, ByteBuffer ComAdrData, int FrmHandle);
    /**
     * Original signature : <code>int WriteScanTime(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 116</i><br>
     * @deprecated use the safer methods {@link #WriteScanTime(ByteBuffer, ByteBuffer, int)} and {@link #WriteScanTime(com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int WriteScanTime(Pointer address, Pointer ScanTime, int FrmHandle);
    /**
     * Original signature : <code>int WriteScanTime(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 116</i>
     */
    int WriteScanTime(ByteBuffer address, ByteBuffer ScanTime, int FrmHandle);
    /**
     * Original signature : <code>int Writebaud(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 119</i><br>
     * @deprecated use the safer methods {@link #Writebaud(ByteBuffer, ByteBuffer, int)} and {@link #Writebaud(com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int Writebaud(Pointer address, Pointer baud, int FrmHandle);
    /**
     * Original signature : <code>int Writebaud(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 119</i>
     */
    int Writebaud(ByteBuffer address, ByteBuffer baud, int FrmHandle);
    /**
     * Original signature : <code>int SetPowerDbm(unsigned char*, unsigned char, int)</code><br>
     * <i>native declaration : line 122</i><br>
     * @deprecated use the safer methods {@link #SetPowerDbm(ByteBuffer, byte, int)} and {@link #SetPowerDbm(com.sun.jna.Pointer, byte, int)} instead
     */
    @Deprecated
    int SetPowerDbm(Pointer address, byte PowerDbm, int FrmHandle);
    /**
     * Original signature : <code>int SetPowerDbm(unsigned char*, unsigned char, int)</code><br>
     * <i>native declaration : line 122</i>
     */
    int SetPowerDbm(ByteBuffer address, byte PowerDbm, int FrmHandle);
    /**
     * Original signature : <code>int BuzzerAndLEDControl(unsigned char*, unsigned char, unsigned char, unsigned char, int)</code><br>
     * <i>native declaration : line 125</i><br>
     * @deprecated use the safer methods {@link #BuzzerAndLEDControl(ByteBuffer, byte, byte, byte, int)} and {@link #BuzzerAndLEDControl(com.sun.jna.Pointer, byte, byte, byte, int)} instead
     */
    @Deprecated
    int BuzzerAndLEDControl(Pointer address, byte AvtiveTime, byte SilentTime, byte Times, int FrmHandle);
    /**
     * Original signature : <code>int BuzzerAndLEDControl(unsigned char*, unsigned char, unsigned char, unsigned char, int)</code><br>
     * <i>native declaration : line 125</i>
     */
    int BuzzerAndLEDControl(ByteBuffer address, byte AvtiveTime, byte SilentTime, byte Times, int FrmHandle);
    /**
     * Original signature : <code>int EraseCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 130</i><br>
     * @deprecated use the safer methods {@link #EraseCard_G2(ByteBuffer, ByteBuffer, byte, byte, byte, ByteBuffer, byte, byte, byte, byte, IntBuffer, int)} and {@link #EraseCard_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int EraseCard_G2(Pointer address, Pointer EPC, byte Mem, byte WordPtr, byte Num, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int EraseCard_G2(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 130</i>
     */
    int EraseCard_G2(ByteBuffer address, ByteBuffer EPC, byte Mem, byte WordPtr, byte Num, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteEPC_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 142</i><br>
     * @deprecated use the safer methods {@link #WriteEPC_G2(ByteBuffer, ByteBuffer, ByteBuffer, byte, IntBuffer, int)} and {@link #WriteEPC_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int WriteEPC_G2(Pointer address, Pointer Password, Pointer WriteEPC, byte WriteEPClen, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteEPC_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 142</i>
     */
    int WriteEPC_G2(ByteBuffer address, ByteBuffer Password, ByteBuffer WriteEPC, byte WriteEPClen, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int DestroyCard_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 148</i><br>
     * @deprecated use the safer methods {@link #DestroyCard_G2(ByteBuffer, ByteBuffer, ByteBuffer, byte, byte, byte, byte, IntBuffer, int)} and {@link #DestroyCard_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int DestroyCard_G2(Pointer address, Pointer EPC, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int DestroyCard_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 148</i>
     */
    int DestroyCard_G2(ByteBuffer address, ByteBuffer EPC, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetReadProtect_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 157</i><br>
     * @deprecated use the safer methods {@link #SetReadProtect_G2(ByteBuffer, ByteBuffer, ByteBuffer, byte, byte, byte, byte, IntBuffer, int)} and {@link #SetReadProtect_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int SetReadProtect_G2(Pointer address, Pointer EPC, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetReadProtect_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 157</i>
     */
    int SetReadProtect_G2(ByteBuffer address, ByteBuffer EPC, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetMultiReadProtect_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 166</i><br>
     * @deprecated use the safer methods {@link #SetMultiReadProtect_G2(ByteBuffer, ByteBuffer, IntBuffer, int)} and {@link #SetMultiReadProtect_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int SetMultiReadProtect_G2(Pointer address, Pointer Password, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int SetMultiReadProtect_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 166</i>
     */
    int SetMultiReadProtect_G2(ByteBuffer address, ByteBuffer Password, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int RemoveReadProtect_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 170</i><br>
     * @deprecated use the safer methods {@link #RemoveReadProtect_G2(ByteBuffer, ByteBuffer, IntBuffer, int)} and {@link #RemoveReadProtect_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int RemoveReadProtect_G2(Pointer address, Pointer Password, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int RemoveReadProtect_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 170</i>
     */
    int RemoveReadProtect_G2(ByteBuffer address, ByteBuffer Password, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckReadProtected_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 174</i><br>
     * @deprecated use the safer methods {@link #CheckReadProtected_G2(ByteBuffer, ByteBuffer, IntBuffer, int)} and {@link #CheckReadProtected_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int CheckReadProtected_G2(Pointer address, Pointer readpro, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckReadProtected_G2(unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 174</i>
     */
    int CheckReadProtected_G2(ByteBuffer address, ByteBuffer readpro, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int LockUserBlock_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 178</i><br>
     * @deprecated use the safer methods {@link #LockUserBlock_G2(ByteBuffer, ByteBuffer, ByteBuffer, byte, byte, byte, byte, byte, IntBuffer, int)} and {@link #LockUserBlock_G2(com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, byte, byte, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int LockUserBlock_G2(Pointer address, Pointer EPC, Pointer Password, byte maskadr, byte maskLen, byte maskFlag, byte WrdPointer, byte EPClength, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int LockUserBlock_G2(unsigned char*, unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 178</i>
     */
    int LockUserBlock_G2(ByteBuffer address, ByteBuffer EPC, ByteBuffer Password, byte maskadr, byte maskLen, byte maskFlag, byte WrdPointer, byte EPClength, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int Inventory_6B(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 189</i><br>
     * @deprecated use the safer methods {@link #Inventory_6B(ByteBuffer, ByteBuffer, int)} and {@link #Inventory_6B(com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int Inventory_6B(Pointer address, Pointer ID_6B, int FrmHandle);
    /**
     * Original signature : <code>int Inventory_6B(unsigned char*, unsigned char*, int)</code><br>
     * <i>native declaration : line 189</i>
     */
    int Inventory_6B(ByteBuffer address, ByteBuffer ID_6B, int FrmHandle);
    /**
     * Original signature : <code>int inventory2_6B(unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 193</i><br>
     * @deprecated use the safer methods {@link #inventory2_6B(ByteBuffer, byte, byte, byte, ByteBuffer, ByteBuffer, IntBuffer, int)} and {@link #inventory2_6B(com.sun.jna.Pointer, byte, byte, byte, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int inventory2_6B(Pointer address, byte Condition, byte StartAddress, byte mask, Pointer ConditionContent, Pointer ID_6B, IntByReference Cardnum, int FrmHandle);
    /**
     * Original signature : <code>int inventory2_6B(unsigned char*, unsigned char, unsigned char, unsigned char, unsigned char*, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 193</i>
     */
    int inventory2_6B(ByteBuffer address, byte Condition, byte StartAddress, byte mask, ByteBuffer ConditionContent, ByteBuffer ID_6B, IntBuffer Cardnum, int FrmHandle);
    /**
     * Original signature : <code>int ReadCard_6B(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 202</i><br>
     * @deprecated use the safer methods {@link #ReadCard_6B(ByteBuffer, ByteBuffer, byte, byte, ByteBuffer, IntBuffer, int)} and {@link #ReadCard_6B(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, byte, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int ReadCard_6B(Pointer address, Pointer ID_6B, byte StartAddress, byte Num, Pointer Data, IntByReference errorcode, int FrmHandle);
    /**
     * Original signature : <code>int ReadCard_6B(unsigned char*, unsigned char*, unsigned char, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 202</i>
     */
    int ReadCard_6B(ByteBuffer address, ByteBuffer ID_6B, byte StartAddress, byte Num, ByteBuffer Data, IntBuffer errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteCard_6B(unsigned char*, unsigned char*, unsigned char, unsigned char*, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 210</i><br>
     * @deprecated use the safer methods {@link #WriteCard_6B(ByteBuffer, ByteBuffer, byte, ByteBuffer, byte, ByteBuffer, IntBuffer, int)} and {@link #WriteCard_6B(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, com.sun.jna.Pointer, byte, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int WriteCard_6B(Pointer address, Pointer ID_6B, byte StartAddress, Pointer Writedata, byte Writedatalen, Pointer writtenbyte, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int WriteCard_6B(unsigned char*, unsigned char*, unsigned char, unsigned char*, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 210</i>
     */
    int WriteCard_6B(ByteBuffer address, ByteBuffer ID_6B, byte StartAddress, ByteBuffer Writedata, byte Writedatalen, ByteBuffer writtenbyte, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int LockByte_6B(unsigned char*, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 219</i><br>
     * @deprecated use the safer methods {@link #LockByte_6B(ByteBuffer, ByteBuffer, byte, IntBuffer, int)} and {@link #LockByte_6B(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int LockByte_6B(Pointer address, Pointer ID_6B, byte StartAddress, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int LockByte_6B(unsigned char*, unsigned char*, unsigned char, int*, int)</code><br>
     * <i>native declaration : line 219</i>
     */
    int LockByte_6B(ByteBuffer address, ByteBuffer ID_6B, byte StartAddress, IntBuffer Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckLock_6B(unsigned char*, unsigned char*, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 225</i><br>
     * @deprecated use the safer methods {@link #CheckLock_6B(ByteBuffer, ByteBuffer, byte, ByteBuffer, IntBuffer, int)} and {@link #CheckLock_6B(com.sun.jna.Pointer, com.sun.jna.Pointer, byte, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, int)} instead
     */
    @Deprecated
    int CheckLock_6B(Pointer address, Pointer ID_6B, byte StartAddress, Pointer ReLockState, IntByReference Errorcode, int FrmHandle);
    /**
     * Original signature : <code>int CheckLock_6B(unsigned char*, unsigned char*, unsigned char, unsigned char*, int*, int)</code><br>
     * <i>native declaration : line 225</i>
     */
    int CheckLock_6B(ByteBuffer address, ByteBuffer ID_6B, byte StartAddress, ByteBuffer ReLockState, IntBuffer Errorcode, int FrmHandle);
    public static final GlobalInt nRRU9809 = new GlobalInt(ComRfidRru9809Library.JNA_NATIVE_LIB, "nRRU9809");
}
