package sevts.terminal.usbrelay;

import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;

/**
 * usb relay board info structure<br>
 * <i>native declaration : usb_relay_device.h:27</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class usb_relay_device_info extends Structure<usb_relay_device_info, usb_relay_device_info.ByValue, usb_relay_device_info.ByReference > {
	/// C type : unsigned char*
	public Pointer serial_number;
	/// C type : char*
	public Pointer device_path;
	/**
	 * @see usb_relay_device_type<br>
	 * C type : usb_relay_device_type
	 */
	public int type;
	/// C type : usb_relay_device_info*
	public ByReference next;
	public usb_relay_device_info() {
		super();
	}
	/**
	 * @param serial_number C type : unsigned char*<br>
	 * @param device_path C type : char*<br>
	 * @param type @see usb_relay_device_type<br>
	 * C type : usb_relay_device_type<br>
	 * @param next C type : usb_relay_device_info*
	 */
	public usb_relay_device_info(Pointer serial_number, Pointer device_path, int type, ByReference next) {
		super();
		this.serial_number = serial_number;
		this.device_path = device_path;
		this.type = type;
		this.next = next;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected usb_relay_device_info newInstance() { return new usb_relay_device_info(); }
	public static usb_relay_device_info[] newArray(int arrayLength) {
		return Structure.newArray(usb_relay_device_info.class, arrayLength);
	}
	public static class ByReference extends usb_relay_device_info implements Structure.ByReference {
		
	};
	public static class ByValue extends usb_relay_device_info implements Structure.ByValue {
		
	};
}
